### ISSUE TITLE
Dependency tree

### ISSUE THREAD

**Issue by giordano** [ianshmean/GTK3Builder#1]
Please, update as needed :wink:

Updated by Ian!

- [x] GLib (https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/Glib/build_tarballs.jl)
- [ ] [GdkPixbuf](https://github.com/ianshmean/GdkPixbufBuilder)
  - [x] [shared-mime-info](https://github.com/ianshmean/SharedMimeInfoBuilder) ([released](https://github.com/ianshmean/SharedMimeInfoBuilder/releases/tag/v1.0.0))
- [x] Pango (https://github.com/JuliaPackaging/Yggdrasil/pull/41)
- [ ] at-spi2-atk (meson build) http://www.linuxfromscratch.org/blfs/view/cvs/x/at-spi2-atk.html
  - [ ] at-spi2-core-2.32.1 (meson build) http://www.linuxfromscratch.org/blfs/view/cvs/x/at-spi2-core.html
  - [ ] ATK-2.32.0 (meson build) http://www.linuxfromscratch.org/blfs/view/cvs/x/atk.html
- [ ] libepoxy-1.5.3 (meson build) http://www.linuxfromscratch.org/blfs/view/svn/x/libepoxy.html

http://www.linuxfromscratch.org/blfs/view/cvs/x/gtk3.html

These resources can be useful:
- http://www.linuxfromscratch.org/blfs/view/cvs/x/gtk3.html
- https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gtk3
- https://salsa.debian.org/gnome-team/gtk3/blob/debian/master/debian/rules
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/gtk+3.rb
- https://github.com/spack/spack/blob/master/var/spack/repos/builtin/packages/gtkplus/package.py

**Comment by IanButterworth** [comment]
Required for [GdkPixBuf](http://www.linuxfromscratch.org/blfs/view/8.3/x/gdk-pixbuf.html):
- https://github.com/ianshmean/SharedMimeInfoBuilder (seems to be working)

**Comment by IanButterworth** [comment]
GdkPixBuf (awaiting shared-mine-info release) https://github.com/ianshmean/GdkPixbufBuilder

**Comment by IanButterworth** [comment]
It's not ATK that's the main dep, it's `at-spi2-atk-2.32.0` which is dep on `at-spi2-core-2.32.1` and `ATK-2.32.0`

All three are Meson builds!

http://www.linuxfromscratch.org/blfs/view/cvs/x/gtk3.html

**Comment by giordano** [comment]
For meson, I got a stub cross file, but I still need to test it: https://github.com/JuliaPackaging/Yggdrasil/pull/43.

Note that some of the packages that Linux from scratch suggests to build with meson can probably be built with autotools, too, they just recommend the fanciest option.  If meson support in BB won't be good enough, we can try to build the latest versions of the packages that support autotools

**Comment by giordano** [comment]
I moved the issue to https://github.com/JuliaPackaging/Yggdrasil/issues/62.  Gtk is going to be built with the future BinaryBuilder, so it's better to have everything in Yggdrasil.
